import "server-only"
import { randomBytes } from "node:crypto"
import { db } from "@/lib/db"
import { hashPassword } from "@/lib/auth/password"
import { requiredString, optionalEmail, optionalString, requiredEnum } from "@/lib/platform/import/parsers"
import type { ImporterDefinition, RowIssue } from "@/lib/platform/import/types"

const SUPER_ADMIN_ROLE_NAME = "super admin"
const STATUSES = ["active", "inactive"] as const

/**
 * P4.9.2 §29-33 — HIGH RISK, SECURITY SENSITIVE: User/RBAC import. Mapped
 * against `User`/`UserRole`/`UserBranchAccess` (prisma/schema.prisma).
 *
 * §31 password safety: NO password of any kind is ever accepted from the
 * CSV, generated as a "default," or persisted anywhere retrievable. Each
 * created User gets `passwordHash` set to the hash of a cryptographically
 * random value that is generated, hashed, and immediately discarded in the
 * same expression — never assigned to a variable, never logged, never
 * written to ImportJob/ImportJobError/audit/preview. The account is
 * therefore genuinely unusable until activated. Activation reuses the
 * EXISTING self-service "Forgot password" flow at /login (auth/service.ts's
 * `requestPasswordReset`) — this importer deliberately does not mint its
 * own reset token or invitation link at import time (that would be a
 * second, parallel, unaudited credential-delivery path); it creates only
 * the account shell. Real email delivery for that flow still depends on a
 * configured transactional email provider — this import does not change or
 * bypass that already-documented limitation (docs/COMMERCIAL_READINESS.md).
 *
 * §32 privilege escalation: bulk-creating a "Super Admin" account is
 * prohibited outright, regardless of the importing actor's own role —
 * matching the recommendation to prefer prohibiting it entirely rather
 * than trying to build an "already-authorized Super Admin may bulk-create
 * more Super Admins" carve-out. Every referenced role/branch must already
 * exist in the SAME organization the importing session belongs to
 * (resolved via maps scoped to that organization only, the same pattern
 * every other importer's branchByCode/departmentByName already uses).
 */
export type UserImportRow = {
  email: string
  username: string | null
  firstName: string
  lastName: string
  status: (typeof STATUSES)[number]
  roleIds: string[]
  branchIds: string[]
  employeeId: string | null
}

export function createUsersImporter(
  roleIdByName: Map<string, string>,
  branchByCode: Map<string, string>,
  employeeByNumber: Map<string, string>
): ImporterDefinition<UserImportRow> {
  return {
    type: "users",
    group: "Operations",
    riskLevel: "high",
    confirmationText: "I understand this import creates real staff login accounts (with no usable password — activation happens through the existing password reset flow) and grants them the roles/branch access listed in the file.",
    templateVersion: "users-v1",
    label: "Users",
    requiredHeaders: ["email", "firstName", "lastName", "roleNames", "branchCodes"],
    optionalHeaders: ["username", "status", "employeeNumber"],
    helpText: [
      "email must be unique within your organization.",
      "roleNames: one or more existing role names, separated by \";\". Bulk-creating a \"Super Admin\" account is not permitted — create that account interactively if genuinely needed.",
      "branchCodes: one or more existing branch codes, separated by \";\".",
      "status (optional, default active): active or inactive.",
      "employeeNumber (optional): links this login to an existing Employee record.",
      "No password is accepted or generated by this import. Created accounts have no usable password — activate them afterward using the normal \"Forgot password\" flow at the login page (requires a configured email provider to deliver automatically; otherwise an administrator relays the reset link manually).",
    ],
    async parseRow(raw) {
      const issues: RowIssue[] = []
      const push = (i: RowIssue | null) => i && issues.push(i)

      const email = optionalEmail(raw.email, "email")
      if (!raw.email?.trim()) issues.push({ field: "email", code: "REQUIRED_FIELD", message: "email is required." })
      else push(email.error)
      const firstName = requiredString(raw.firstName, "firstName", 100)
      push(firstName.error)
      const lastName = requiredString(raw.lastName, "lastName", 100)
      push(lastName.error)
      const status = raw.status?.trim() ? requiredEnum(raw.status, "status", STATUSES) : { value: "active" as const, error: null }
      push(status.error)

      const roleNamesRaw = raw.roleNames?.trim()
      const roleIds: string[] = []
      let hasSuperAdmin = false
      if (!roleNamesRaw) {
        issues.push({ field: "roleNames", code: "REQUIRED_FIELD", message: "roleNames is required (at least one role)." })
      } else {
        for (const roleName of roleNamesRaw.split(";").map((r) => r.trim()).filter(Boolean)) {
          if (roleName.toLowerCase() === SUPER_ADMIN_ROLE_NAME) {
            hasSuperAdmin = true
            continue
          }
          const id = roleIdByName.get(roleName.toLowerCase())
          if (!id) issues.push({ field: "roleNames", code: "UNKNOWN_REFERENCE", message: `roleNames: "${roleName}" does not match any existing role in this organization.` })
          else roleIds.push(id)
        }
      }
      if (hasSuperAdmin) {
        issues.push({ field: "roleNames", code: "BUSINESS_RULE", message: "Bulk-creating a \"Super Admin\" account is not permitted through this import — create it interactively if genuinely needed." })
      }

      const branchCodesRaw = raw.branchCodes?.trim()
      const branchIds: string[] = []
      if (!branchCodesRaw) {
        issues.push({ field: "branchCodes", code: "REQUIRED_FIELD", message: "branchCodes is required (at least one branch)." })
      } else {
        for (const code of branchCodesRaw.split(";").map((c) => c.trim()).filter(Boolean)) {
          const id = branchByCode.get(code.toLowerCase())
          if (!id) issues.push({ field: "branchCodes", code: "UNKNOWN_BRANCH", message: `branchCodes: "${code}" does not match any branch in this organization.` })
          else branchIds.push(id)
        }
      }

      let employeeId: string | null = null
      const empRaw = raw.employeeNumber?.trim()
      if (empRaw) {
        employeeId = employeeByNumber.get(empRaw.toLowerCase()) ?? null
        if (!employeeId) issues.push({ field: "employeeNumber", code: "UNKNOWN_REFERENCE", message: `employeeNumber "${empRaw}" does not match any existing employee.` })
      }

      if (issues.length > 0) return { normalized: null, issues }
      return {
        normalized: {
          email: email.value!,
          username: optionalString(raw.username, "username", 100).value,
          firstName: firstName.value!,
          lastName: lastName.value!,
          status: status.value!,
          roleIds: [...new Set(roleIds)],
          branchIds: [...new Set(branchIds)],
          employeeId,
        },
        issues: [],
      }
    },

    async detectDuplicates(rows, ctx) {
      const candidates = rows.filter((r) => r.normalized)
      if (candidates.length === 0) return
      const emails = [...new Set(candidates.map((r) => r.normalized!.email))]
      const employeeIds = [...new Set(candidates.map((r) => r.normalized!.employeeId).filter((e): e is string => !!e))]
      const [existingByEmail, existingByEmployee] = await Promise.all([
        db.user.findMany({ where: { organizationId: ctx.organizationId, email: { in: emails } }, select: { email: true } }),
        employeeIds.length > 0 ? db.user.findMany({ where: { organizationId: ctx.organizationId, employeeProfile: { id: { in: employeeIds } } }, select: { employeeProfile: { select: { id: true } } } }) : [],
      ])
      const existingEmails = new Set(existingByEmail.map((e) => e.email.toLowerCase()))
      const existingEmployeeIds = new Set(existingByEmployee.map((e) => e.employeeProfile?.id).filter((e): e is string => !!e))

      const seenEmails = new Set<string>()
      const seenEmployees = new Set<string>()
      for (const row of candidates) {
        const n = row.normalized!
        const email = n.email.toLowerCase()
        if (existingEmails.has(email)) {
          row.duplicate = true
          row.duplicateReason = `A user with email "${n.email}" already exists.`
          continue
        }
        if (seenEmails.has(email)) {
          row.duplicate = true
          row.duplicateReason = "Duplicate email within this same file."
          continue
        }
        if (n.employeeId && existingEmployeeIds.has(n.employeeId)) {
          row.duplicate = true
          row.duplicateReason = "This employee already has a linked user account."
          continue
        }
        if (n.employeeId && seenEmployees.has(n.employeeId)) {
          row.duplicate = true
          row.duplicateReason = "Duplicate employeeNumber within this same file."
          continue
        }
        seenEmails.add(email)
        if (n.employeeId) seenEmployees.add(n.employeeId)
      }
    },

    // P4.9.2 — argon2id hashing is deliberately slow (the whole point of
    // the algorithm); doing 200 of them sequentially inside one open DB
    // transaction genuinely exceeded Prisma's interactive-transaction
    // timeout on a realistic 1,000-row import (found by this phase's own
    // performance test, not theoretical). Hashed here, in parallel,
    // entirely before any transaction opens — see
    // ImporterDefinition.prepareBatch's own doc comment.
    async prepareBatch(rows) {
      const entries = await Promise.all(rows.map(async (row) => [row.rowNumber, await hashPassword(randomBytes(32).toString("hex"))] as const))
      return new Map(entries)
    },

    async commitBatch(tx, rows, ctx, _jobId, prepared) {
      let imported = 0
      for (const row of rows) {
        const n = row.normalized!
        // Precomputed by prepareBatch above — never assigned to a
        // module-level variable, never logged, never returned to the caller.
        const passwordHash = prepared!.get(row.rowNumber) as string
        const created = await tx.user.create({
          data: {
            organizationId: ctx.organizationId,
            email: n.email,
            username: n.username,
            firstName: n.firstName,
            lastName: n.lastName,
            status: n.status,
            passwordHash,
            employeeProfile: n.employeeId ? { connect: { id: n.employeeId } } : undefined,
          },
        })
        if (n.roleIds.length > 0) {
          await tx.userRole.createMany({ data: n.roleIds.map((roleId) => ({ userId: created.id, roleId })) })
        }
        if (n.branchIds.length > 0) {
          await tx.userBranchAccess.createMany({ data: n.branchIds.map((branchId) => ({ userId: created.id, branchId })) })
        }
        imported++
      }
      return { imported, skipped: 0 }
    },

    // P4.9.2 §41 — accounts/roles/branches breakdown, never any credential data.
    computeDomainSummary(rows) {
      const committable = rows.filter((r) => r.issues.length === 0 && !r.duplicate && r.normalized)
      const roleIds = new Set<string>()
      const branchIds = new Set<string>()
      for (const r of committable) {
        r.normalized!.roleIds.forEach((id) => roleIds.add(id))
        r.normalized!.branchIds.forEach((id) => branchIds.add(id))
      }
      return [
        { label: "Accounts to create", value: String(committable.length) },
        { label: "Distinct roles referenced", value: String(roleIds.size) },
        { label: "Distinct branches referenced", value: String(branchIds.size) },
      ]
    },
  }
}
