import { test, expect } from "@playwright/test"
import { loginAsClinicUser, readFixture, patchFixture, withDb, type PilotFixture } from "./fixtures"

/**
 * P5.3 Step 11/12/13 — billing/POS, payments, refunds, and doctor
 * commission UAT, chained against Aisha's real charges (consultation +
 * lab + pharmacy, all generated by earlier stages). Commission
 * authorize/complete uses the super admin — this pilot clinic has no
 * separate Clinic Manager user (not in the command's own required role
 * list), and Super Admin's "ALL" permissions cover `refund.authorize`
 * realistically for a small clinic with no dedicated finance manager.
 */
test.describe.serial("P5.3 Billing / POS / Payments / Refunds / Commissions UAT", () => {
  let fixture: PilotFixture
  let invoiceId: string
  let paymentId: string

  test("set up a 10% commission rule for doctor1 on the consultation service (collected-revenue basis — fires on payment, not invoice)", async ({ page }) => {
    test.setTimeout(90_000)
    fixture = readFixture()
    await loginAsClinicUser(page, fixture.users.superAdmin.email, fixture.users.superAdmin.password)
    await page.goto("/commissions")
    await page.getByRole("button", { name: "New commission rule" }).click()
    {
      const dlg = page.getByRole("dialog")
      await dlg.getByRole("combobox", { name: "Provider (blank = all)" }).click()
      await page.getByRole("option", { name: /Dana Doctor/ }).click()
      await dlg.getByRole("combobox", { name: "Service (blank = all)" }).click()
      await page.getByRole("option", { name: fixture.services.consultationName }).click()
      // Type defaults to "percentage", Basis defaults to "collected revenue" — both already correct.
      await dlg.getByLabel("Percentage rate (0–1, e.g. 0.10 = 10%)").fill("0.10")
      await dlg.getByRole("button", { name: "Create rule" }).click()
    }
    await expect(page.getByRole("dialog")).toBeHidden({ timeout: 10_000 })

    const rule = await withDb((db) =>
      db.query<{ id: string }>(`select id from commission_rule where organization_id=$1 and provider_id=$2 order by created_at desc limit 1`, [
        fixture.organizationId,
        fixture.providers.doctor1Id,
      ])
    )
    expect(rule.rows[0]?.id, "commission rule must exist in the database").toBeTruthy()
  })

  test("open a cashier register, generate an invoice from Aisha's pending charges (consultation + lab + pharmacy), and record a full cash payment", async ({ page }) => {
    test.setTimeout(120_000)
    fixture = readFixture()
    await loginAsClinicUser(page, fixture.users.receptionist.email, fixture.users.receptionist.password)
    await page.goto("/pos")

    const registerBtn = page.getByRole("button", { name: "Open register" })
    if (await registerBtn.isVisible().catch(() => false)) {
      await page.getByRole("combobox", { name: "Branch" }).click()
      await page.getByRole("option", { name: fixture.branchA.name }).click()
      await page.getByLabel("Opening cash").fill("500")
      await registerBtn.click()
      await expect(page.getByRole("button", { name: "Close register" })).toBeVisible({ timeout: 15_000 })
    }

    // Search for Aisha and generate the invoice from her pending charges.
    await page.goto(`/pos?patientId=${fixture.patients.aisha}`)
    // Not the raw input[name="chargeIds"] — shadcn's Checkbox hides the
    // native input (aria-hidden) and renders a visible role="checkbox"
    // button on top of it, which intercepts pointer events on the hidden
    // input and blocks .check() from ever landing.
    const chargeCheckboxes = page.getByRole("checkbox")
    const chargeCount = await chargeCheckboxes.count()
    expect(chargeCount, "at least the consultation, lab, and pharmacy charges from earlier stages must be pending").toBeGreaterThanOrEqual(1)
    for (let i = 0; i < chargeCount; i++) await chargeCheckboxes.nth(i).click()
    await page.getByRole("button", { name: /Create Invoice \(\d+\)/ }).click()
    await expect(page).toHaveURL(/\/invoices\/[^/]+$/, { timeout: 15_000 })
    invoiceId = page.url().split("/").pop()!

    const invoiceRow = await withDb((db) =>
      db.query<{ total_amount: string; paid_amount: string; status: string }>(`select total_amount, paid_amount, status from invoice where id=$1`, [invoiceId])
    )
    expect(invoiceRow.rows).toHaveLength(1)
    const totalAmount = invoiceRow.rows[0].total_amount

    // record-payment-dialog.tsx already defaults its one tender to
    // { method: "cash", amount: outstanding.toFixed(2) } — exactly the full
    // cash payment this test wants, so no field interaction is needed
    // before submitting. (Its "Method" <Label> also has no htmlFor tying it
    // to the Select, the same unlabeled-field gap found in the prescription
    // dialog — getByRole("combobox", { name: "Method" }) can never resolve.)
    await page.getByRole("button", { name: "Record payment" }).click()
    await page.getByRole("dialog").getByRole("button", { name: "Record payment" }).click()
    await expect(page.getByRole("dialog")).toBeHidden({ timeout: 10_000 })

    const afterPayment = await withDb((db) => db.query<{ paid_amount: string; status: string }>(`select paid_amount, status from invoice where id=$1`, [invoiceId]))
    expect(afterPayment.rows[0].status).toBe("paid")
    expect(afterPayment.rows[0].paid_amount).toBe(totalAmount)

    const payment = await withDb((db) =>
      db.query<{ id: string }>(
        `select p.id from payment p join payment_allocation pa on pa.payment_id = p.id where pa.invoice_id=$1 order by p.received_at desc limit 1`,
        [invoiceId]
      )
    )
    paymentId = payment.rows[0].id

    patchFixture({ patients: { ...fixture.patients, aishaInvoiceId: invoiceId, aishaPaymentId: paymentId } })
  })

  test("REQUIRED — the invoice and payment each post a balanced journal to the correct organization/branch, and doctor1 accrues the expected commission on payment", async ({ page }) => {
    fixture = readFixture()
    invoiceId = fixture.patients.aishaInvoiceId

    const journals = await withDb((db) =>
      db.query<{ id: string; debit_total: string; credit_total: string; organization_id: string; branch_id: string }>(
        `select j.id, j.organization_id, j.branch_id,
                (select coalesce(sum(debit),0) from journal_line where journal_id=j.id)::text as debit_total,
                (select coalesce(sum(credit),0) from journal_line where journal_id=j.id)::text as credit_total
         from journal j
         where j.organization_id=$1 and j.reference_id in ($2, $3)`,
        [fixture.organizationId, invoiceId, fixture.patients.aishaPaymentId]
      )
    )
    expect(journals.rows.length, "both the invoice-issued and payment-received journals must exist").toBeGreaterThanOrEqual(2)
    for (const j of journals.rows) {
      expect(j.debit_total, `journal ${j.id} must balance — debit must equal credit`).toBe(j.credit_total)
      expect(j.organization_id).toBe(fixture.organizationId)
      expect(j.branch_id, "every journal must carry the correct branch, not just organization").toBe(fixture.branchA.id)
    }

    const accrual = await withDb((db) =>
      db.query<{ amount: string; status: string }>(
        `select amount, status from commission_accrual where organization_id=$1 and provider_id=$2 order by accrued_at desc limit 1`,
        [fixture.organizationId, fixture.providers.doctor1Id]
      )
    )
    expect(accrual.rows.length, "a commission accrual must exist for doctor1 after payment (collected_revenue basis)").toBeGreaterThanOrEqual(1)
    expect(Number(accrual.rows[0].amount)).toBeGreaterThan(0)
    expect(accrual.rows[0].status).toBe("pending")
  })

  test("request a partial refund, authorize and complete it, and verify the financial reversal AND commission clawback — no duplicate commission left standing", async ({ page }) => {
    test.setTimeout(120_000)
    fixture = readFixture()
    invoiceId = fixture.patients.aishaInvoiceId

    const accrualBefore = await withDb((db) =>
      db.query<{ count: string }>(`select count(*)::text from commission_accrual where organization_id=$1 and provider_id=$2`, [fixture.organizationId, fixture.providers.doctor1Id])
    )

    await loginAsClinicUser(page, fixture.users.receptionist.email, fixture.users.receptionist.password)
    await page.goto(`/invoices/${invoiceId}`)
    await page.getByRole("button", { name: "Request refund" }).click()
    {
      const dlg = page.getByRole("dialog")
      await dlg.getByLabel("Amount").fill("5")
      await dlg.getByLabel("Reason").fill("Patient overcharged for one item — UAT synthetic refund")
      await dlg.getByRole("button", { name: "Request refund" }).click()
    }
    await expect(page.getByRole("dialog")).toBeHidden({ timeout: 10_000 })

    const refund = await withDb((db) =>
      db.query<{ id: string; status: string }>(`select id, status from refund where organization_id=$1 order by requested_at desc limit 1`, [fixture.organizationId])
    )
    const refundId = refund.rows[0].id
    expect(refund.rows[0].status).toBe("requested")

    // Authorize + complete as super admin (no dedicated Clinic Manager user in this pilot).
    await loginAsClinicUser(page, fixture.users.superAdmin.email, fixture.users.superAdmin.password)
    await page.goto(`/invoices/${invoiceId}`)
    await page.getByRole("button", { name: "Authorize" }).click()
    await expect(page.getByText(/authorized/i).first()).toBeVisible({ timeout: 10_000 })
    await page.getByRole("button", { name: "Complete" }).click()
    await expect(page.getByText(/completed/i).first()).toBeVisible({ timeout: 10_000 })

    const afterRefund = await withDb((db) => db.query<{ status: string; paid_amount: string }>(`select status, paid_amount from invoice where id=$1`, [invoiceId]))
    expect(afterRefund.rows[0].status).not.toBe("void")

    const refundJournal = await withDb((db) =>
      db.query<{ debit_total: string; credit_total: string }>(
        `select (select coalesce(sum(debit),0) from journal_line where journal_id=j.id)::text as debit_total,
                (select coalesce(sum(credit),0) from journal_line where journal_id=j.id)::text as credit_total
         from journal j where j.organization_id=$1 and j.reference_id=$2`,
        [fixture.organizationId, refundId]
      )
    )
    expect(refundJournal.rows.length, "the refund must post its own balanced reversal journal").toBeGreaterThanOrEqual(1)
    expect(refundJournal.rows[0].debit_total).toBe(refundJournal.rows[0].credit_total)

    // Commission clawback: a NEW negative-amount reversal row, never mutating the original accrual.
    const accrualAfter = await withDb((db) =>
      db.query<{ count: string; total: string }>(
        `select count(*)::text, coalesce(sum(amount),0)::text as total from commission_accrual where organization_id=$1 and provider_id=$2`,
        [fixture.organizationId, fixture.providers.doctor1Id]
      )
    )
    expect(Number(accrualAfter.rows[0].count), "a reversal accrual row must be added, never deleting/mutating the original").toBeGreaterThan(Number(accrualBefore.rows[0].count))
    const reversalRow = await withDb((db) =>
      db.query<{ amount: string; reversal_of_id: string | null }>(
        `select amount, reversal_of_id from commission_accrual where organization_id=$1 and provider_id=$2 and refund_id=$3`,
        [fixture.organizationId, fixture.providers.doctor1Id, refundId]
      )
    )
    expect(reversalRow.rows.length).toBeGreaterThanOrEqual(1)
    expect(Number(reversalRow.rows[0].amount), "the clawback row's amount must be negative").toBeLessThan(0)
    expect(reversalRow.rows[0].reversal_of_id, "the clawback must reference which original accrual it reverses").toBeTruthy()
  })

  test("close the cashier register and verify expected cash / variance are computed, never left as a manual guess", async ({ page }) => {
    test.setTimeout(90_000)
    fixture = readFixture()
    await loginAsClinicUser(page, fixture.users.receptionist.email, fixture.users.receptionist.password)
    await page.goto("/pos")
    const closeBtn = page.getByRole("button", { name: "Close register" })
    if (!(await closeBtn.isVisible().catch(() => false))) {
      test.skip(true, "no open register for this user/branch to close (already closed or never opened)")
    }
    await closeBtn.click()
    {
      const dlg = page.getByRole("dialog")
      await dlg.getByLabel("Actual cash counted").fill("495")
      await dlg.getByRole("button", { name: "Close register" }).click()
    }
    await expect(page.getByRole("dialog")).toBeHidden({ timeout: 10_000 })

    const session = await withDb((db) =>
      db.query<{ expected_cash: string | null; actual_cash: string | null; variance: string | null; status: string }>(
        `select expected_cash, actual_cash, variance, status from cashier_session where organization_id=$1 order by opened_at desc limit 1`,
        [fixture.organizationId]
      )
    )
    expect(session.rows[0].status).toBe("closed")
    expect(session.rows[0].expected_cash, "expected cash must be server-computed, never left null").not.toBeNull()
    expect(session.rows[0].variance, "variance must be server-computed from expected vs actual").not.toBeNull()
  })
})
